### PR TITLE
Update _examples.md

### PR DESCRIPTION
**Pull request by heytimc**
corrected html formatting

### CODE REVIEW

**Comment by DominicWatson** [comment]
Thanks for this @heytimc. However, this should really not use straight HTML but use our markdown syntax for Lucee syntax highlighting. See: http://docs.lucee.org/docs/content/markdown.html#syntax-highlighting

So, all the code should just be wrapped in triple backticks with the `lucee` dialect appended to the opening ticks. e.g.

    ```lucee
    <cfset blah = "true">
    <!--- etc --->
    ```

Are you able to refactor using this approach?

**Comment by heytimc** [comment]
Urg another different markdown! :( will examine

**Comment by DominicWatson** [comment]
This is not different markdown at all. Standard syntax along with optional lexers which many MD interpreters support.

This also allows us to embed examples directly with TryCF (for things that don't require datasource connections, etc.) which is really powerful.

**Comment by heytimc** [comment]
Great - am just reading up on it, thanks.

**Comment by DominicWatson** [comment]
I made the changes, was then a simple case of wrapping in the highlighting markdown.

**Pull request merged**
