### PR TITLE
Addressing LD-70

### PR DESCRIPTION
**Pull request by ajlemke**
Added algorithms from CFDocs
Added encodings from CFDocs

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@ajlemke Can you confirm you have checked that Lucee supports these algorithms please as I'm not sure myself.

**Comment by ajlemke** [comment]
@andrew-dixon here is a gist from TryCF that encompasses the algorithms and encodings.
http://trycf.com/gist/01603b838430f8796383c8954ab92dc1/lucee?theme=monokai

**Comment by andrew-dixon** [comment]
@ajlemke Thanks.

**Comment by TwentyOneSolutions** [comment]
@andrew-dixon - It's been a while so I don't remember exactly, but in general all of the algorithms that ship with Java should be supported.  See http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html

**Pull request merged**
