### PR TITLE
Update _examples.md

### PR DESCRIPTION
**Pull request by webonix**
cfscript example

### CODE REVIEW

**Comment by DominicWatson** [comment]
Nice work. Couple of quick things before I merge this:

* There is one too many backticks at the end of the code sample, needs to be three not four
* The block of code after '//each - calculate age' is needlessly indented - could you put it on the same level as the code above?

Dominic

**Comment by webonix** [comment]
done

On 25 September 2015 at 16:13, Dominic Watson <notifications@github.com>
wrote:

> Nice work. Couple of quick things before I merge this:
>
>    - There is one too many backticks at the end of the code sample, needs
>    to be three not four
>    - The block of code after '//each - calculate age' is needlessly
>    indented - could you put it on the same level as the code above?
>
> Dominic
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-docs/pull/37#issuecomment-143156100>.
>



-- 

*AJ Mercer*
<webonix:net strength="Industrial" /> <http://webonix.net/> | <webonix:org
community="Open" /> <http://webonix.org/>
http://twitter.com/webonix <http://twitter.com/webonix>

**Comment by DominicWatson** [comment]
Boom, I'll let this build and see how it looks. Have you tried running the build locally? http://docs.lucee.org/docs/build.html Can be useful for verifying formatting, etc. when making multiple changes and doing more than fixing typos, etc.

**Comment by DominicWatson** [comment]
Hm, dang: http://docs.lucee.org/reference/functions/queryeach.html

We have some formatting issues :s. Let me spin it up locally and see if I can fix.

**Comment by webonix** [comment]
whoa!

I did have the docs build set up - will have to get it up to date

On 25 September 2015 at 16:43, Dominic Watson <notifications@github.com>
wrote:

> Hm, dang: http://docs.lucee.org/reference/functions/queryeach.html
>
> We have some formatting issues :s. Let me spin it up locally and see if I
> can fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-docs/pull/37#issuecomment-143162329>.
>



-- 

*AJ Mercer*
<webonix:net strength="Industrial" /> <http://webonix.net/> | <webonix:org
community="Open" /> <http://webonix.org/>
http://twitter.com/webonix <http://twitter.com/webonix>

**Comment by DominicWatson** [comment]
I think the parser is trying to do magic stuff with the `[[` in the `QueryNew(..` bit. I've reformatted and pushed here: https://github.com/lucee/lucee-docs/commit/bfbc1eeaee94d3a3cec75efcc8a595599519227e

Looks like this:

reformatted code

**Comment by DominicWatson** [comment]
Just looking at the example again, is `qryPeopleOldEnough = ...` actually correct? I don't thing that variable is needed and should probably be removed?

**Pull request merged**
