### PR TITLE
Fixing cfstopwatch description and adding example code in both tags and script.

### PR DESCRIPTION
**Pull request by andrew-dixon**
Fixing cfstopwatch description and adding example code in both tags and script.

### CODE REVIEW

**Comment by DominicWatson** [comment]
You should make these code examples runnable with TryCF :). Just add `+trycf` to the lexer name. So `lucee+trycf` or `luceescript+trycf`

**Comment by modius** [comment]
Nice. Will it do that with any Mexer or just the lucee ones?

**Comment by DominicWatson** [comment]
Any Lexer.

**Comment by andrew-dixon** [comment]
@DominicWatson Add the +trycf as requested.

**Pull request merged**
