### PR TITLE
Update _examples.md

### PR DESCRIPTION
**Pull request by webonix**
cfscript

### CODE REVIEW

**Comment by DominicWatson** [comment]
Nice one - like the other example, could you normalize the indentation and remove the extraneous trailing backtick?

**Comment by webonix** [comment]
done

On 25 September 2015 at 16:38, Dominic Watson <notifications@github.com>
wrote:

> Nice one - like the other example, could you normalize the indentation and
> remove the extraneous trailing backtick?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-docs/pull/38#issuecomment-143161410>.
>



-- 

*AJ Mercer*
<webonix:net strength="Industrial" /> <http://webonix.net/> | <webonix:org
community="Open" /> <http://webonix.org/>
http://twitter.com/webonix <http://twitter.com/webonix>

**Comment by DominicWatson** [comment]
The formatting of the query is still an issue - sorry to be a PITA. Could you emulate the formatting that works for QueryEach: https://github.com/lucee/lucee-docs/edit/master/docs/03.reference/01.functions/queryeach/_examples.md and apply this to each of the examples your pulling?

**Comment by webonix** [comment]
I started to set up the docs build on windows (with bash) but ran into JVM
memory issues.

Moved to a Mac, but did not finish - will try again tomorrow.


On 29 September 2015 at 19:42, Dominic Watson <notifications@github.com>
wrote:

> The formatting of the query is still an issue - sorry to be a PITA. Could
> you emulate the formatting that works for QueryEach:
> https://github.com/lucee/lucee-docs/edit/master/docs/03.reference/01.functions/queryeach/_examples.md
> and apply this to each of the examples your pulling?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-docs/pull/38#issuecomment-144034682>.
>



-- 

*AJ Mercer*
<webonix:net strength="Industrial" /> <http://webonix.net/> | <webonix:org
community="Open" /> <http://webonix.org/>
http://twitter.com/webonix <http://twitter.com/webonix>

**Comment by webonix** [comment]
I have go the build running on a Mac now :-)

Another suggestion for you:
in the build doco, have a section got git commands
check out to get started
then how to send a patch


On 29 September 2015 at 19:42, Dominic Watson <notifications@github.com>
wrote:

> The formatting of the query is still an issue - sorry to be a PITA. Could
> you emulate the formatting that works for QueryEach:
> https://github.com/lucee/lucee-docs/edit/master/docs/03.reference/01.functions/queryeach/_examples.md
> and apply this to each of the examples your pulling?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-docs/pull/38#issuecomment-144034682>.
>



-- 

*AJ Mercer*
<webonix:net strength="Industrial" /> <http://webonix.net/> | <webonix:org
community="Open" /> <http://webonix.org/>
http://twitter.com/webonix <http://twitter.com/webonix>

**Comment by webonix** [comment]
better examples coming

**Pull request closed without merging**
