### PR TITLE
A basic example

### PR DESCRIPTION
**Pull request by tomchiverton**

### CODE REVIEW

**Comment by DominicWatson** [comment]
Thanks Tom, merging now.

If you add `lucee` to the backticks though, you'll get lucee specific syntax highlighting (cfm in fact). `luceescript` will give you cfscript syntax highlighting.

```lucee
// code...
```

**Comment by DominicWatson** [comment]
Please also see your other PR which I've left open - will be easier if you ammend the code directly which will update the PR.

**Comment by tomchiverton** [comment]
Lucee-docs doesn't appear to have "issues" any more as an option ?

**Comment by DominicWatson** [comment]
Hey Tom, the issue tracker is over on JIRA: https://luceeserver.atlassian.net/browse/LD

**Pull request merged**
