### PR TITLE
Correct sessionType returned values

### PR DESCRIPTION
**Pull request by cfsimplicity**
GetApplicationMetadata().sessionType returns "jee" not "j2ee"

### CODE REVIEW

**Comment by zspitzer** [comment]
@cfsimplicity this is all a bit odd. `j2ee` is allowed as an alias for `jee`. 

The example on https://docs.lucee.org/reference/functions/getapplicationmetadata.html returns `application` rather than 'cfml'

image

**Comment by cfsimplicity** [comment]
@zspitzer Yes, I'm using `j2ee` when setting `this.sessionType` in Application.cfc, but `GetApplicationMetaData()` can only return one value and it seems to be`jee`.

I hadn't checked the value for a CFML session type, but you're right that's wrong too.

**Comment by zspitzer** [comment]
I've filed a bug about appplication vs cfml https://luceeserver.atlassian.net/browse/LDEV-4223

**Comment by zspitzer** [comment]
PR for 6.0 to return cfml sessionTypes as "cfml"

https://github.com/lucee/Lucee/pull/1836

**Comment by zspitzer** [comment]
@cfsimplicity can you update the j2ee to jee for https://docs.lucee.org/reference/functions/getapplicationsettings.html in your PR as well?

**Comment by zspitzer** [comment]
@cfsimplicity these values are returned for both `getApplicationSettings()` and `getApplicationMetadata()`

**Comment by cfsimplicity** [comment]
Ah, gotcha. Done.

**Pull request merged**
