### PR TITLE
Creating an initial example of the query function

### PR DESCRIPTION
**Pull request by cybersonic**

### CODE REVIEW

**Comment by zspitzer** [comment]
shouldn't examples go in the example section?

**Comment by isapir** [comment]
This is the examples section, no?  

docs/03.reference/01.functions/query/**_examples.md**

**Comment by zspitzer** [comment]
what's the syntax for adding a direct link to QueryNew in the See Also section ?

**Comment by isapir** [comment]
That's one for @DominicWatson ☝️

**Comment by zspitzer** [comment]
Also, is there a standard way of noting this is a lucee only function?

**Comment by DominicWatson** [comment]
@zspitzer to link directly to a tag, find the page ID and use that. In this instance, the id is `tag-query`, so to link from another page:

```
[[tag-query]]
or
[[tag-query|The CFQuery Tag]]

Here is the cfquery tag page in the docs that shows the ID:

https://github.com/lucee/lucee-docs/blob/master/docs/03.reference/02.tags/query/tag.md

**Comment by zspitzer** [comment]
thanks Domenic,  it's case insensitive?

**Pull request merged**
