### PR TITLE
Lucee on CentOS 7

### PR DESCRIPTION
**Pull request by derrick13**

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@derrick13 This will not work as you have simply added the file to the root directory. You need to add it to the correct location under the appropriate folder, etc... see the notes on the repo home page.

**Comment by TwentyOneSolutions** [comment]
why do you need `samba samba-client samba-common htop`?

**Comment by andrew-dixon** [comment]
@TwentyOneSolutions I'm just looking at this now and editing. It hasn't gone on to the docs yet as I didn't notice before merging that the actual article had been deleted. I will have it up, edited down a bit later.

**Comment by TwentyOneSolutions** [comment]
Sounds good.  

Also please note the `user root` in the nginx configuration.  I'm pretty sure that we don't want the web services to run as root ;)

**Comment by michaelheel** [comment]
Please read the comment its not about security its a dev-server. I think its in the first 3 lines.

Samba = smb share to access webroot
Htop = better top, better process manager

**Comment by TwentyOneSolutions** [comment]
I know what Samba and htop are.  but they are not part of "installing Lucee".  they could be part of "setting up your development server", but that's a different "tutorial".

**Comment by michaelheel** [comment]
i would be really happy if you read the introduction before asking:
purpose:
quick howto for setting up "lucee/tomcat8/nginx/sun-jdk8/samba" on CentOS 7.
we dont go for securtiy here its a quick howto to get a clean lucee installation. lets call it a dev-machine. for security rtfm :)

**Comment by andrew-dixon** [comment]
As I said, I'm adapting this now into a Lucee installation guide and will link back to the original blog post from the article for reference.

**Pull request merged**
