### PR TITLE
Update _examples.md

### PR DESCRIPTION
**Pull request by karniolus**
Sample of using function sizeOf.

### CODE REVIEW

**Comment by DominicWatson** [comment]
He @karniolus thanks for the PR. Rather than wrapping the example in `<cfscript>` tags, you can make the example use syntax highlighting and even run in "TryCF" using the technique described here: http://docs.lucee.org/docs/content/markdown.html#embedded-trycf-code-runner.

Are you able to update your PR?

**Comment by karniolus** [comment]
@DominicWatson: Thanks for the answer, I changed the code and updated my PR. Now I'll see if it will work.

**Comment by andrew-dixon** [comment]
Looks good @karniolus, thanks.

**Comment by karniolus** [comment]
@andrew-dixon  you're welcome. I like to help. When will this patch be available on http://docs.lucee.org/reference/functions/sizeof.html?

**Comment by andrew-dixon** [comment]
@karniolus - That odd, should be there within about 10 minutes of the merge, don't really bother checking normally as it just working. 

@DominicWatson Any ideas why this didn't update?

**Pull request merged**
