### PR TITLE
Add example of LSCurrencyFormat()

### PR DESCRIPTION
**Pull request by awayken**

### CODE REVIEW

**Comment by DominicWatson** [comment]
Nice one, thanks for the examples :)

**Comment by awayken** [comment]
You're welcome! I hate how the Adobe ColdFusion examples always show sample code but never give you any sense of what the output would be, so I tried to include that.

**Comment by awayken** [comment]
@DominicWatson How frequently do these code updates get deployed to the Docs server? I saw that you merged my changes but I don't see them [in the LSCurrencyFormat() documentation](http://docs.lucee.org/reference/functions/lscurrencyformat.html).

**Comment by DominicWatson** [comment]
There was a problem with the build so the change did not deploy (another problem is that the build does not currently fail when these problems happen). Changes should deploy as soon as merged into master / pushed to master.

It has now deployed as of this morning (I've been on holidays for the last fortnight). Again, thanks for the contributions :)

**Pull request merged**
