### PR TITLE
Add a GitHub action to lint the YAML files

### PR DESCRIPTION
**Pull request by jbampton**
Run linters only on pull request

Add a YAML lint config file

Lint some YAML

### CODE REVIEW

**Comment by zspitzer** [comment]
is there a way to only run one linter, rather on both push and pr?

we add this in and then there's 4 actions running, we already have 2 linter actions

**Comment by jbampton** [comment]
Hey @zspitzer  I have the lint action working now in just one check 👍

**Comment by jbampton** [comment]
Hey @zspitzer this is ready for review now 👍 

refs #942

**Comment by jbampton** [comment]
Hey @zspitzer can you please review 👍

**Comment by zspitzer** [comment]
let's give it a whirl :)

**Comment by zspitzer** [comment]
@jbampton I have just migrated the docs build process over from Travis to GHA

This run threw some yaml linting errors, but there are no filenames or line numbers?

https://github.com/lucee/lucee-docs/runs/2840354403

**Comment by jbampton** [comment]
Hey @zspitzer that does look strange !!

I will have a look mate.

**Comment by jbampton** [comment]
Ran it on my local machine to see the line numbers.  Will do a PR now and fix them.

Screen Shot 2021-06-17 at 2 37 02 am

**Pull request merged**
