### PR TITLE
Adding httpparams to the examples

### PR DESCRIPTION
**Pull request by cybersonic**

### CODE REVIEW

**Comment by DominicWatson** [comment]
Ha, nice. Merging :)

**Comment by isapir** [comment]
It'd be good to warn about the scope of the result variable when the tag is used inside a function of a Component, and perhaps use the `local` prefix in the example to show how to avoid concurrency issues.

**Comment by cybersonic** [comment]
I don't think that belongs in that specific code result. IT's meant to be self running code and to be honest, I think localmode should be set as default once and for all

**Comment by isapir** [comment]
it can still be self running if you set `result="local.myresult` and then `dump(local.myresult)`.  the problem is that most `localmode` is _not_ the default.

**Comment by cybersonic** [comment]
I get it. I am just saying that in *these*examples it doesnt matter that much. I shall submit a fix to make you happy but the bigger issue is using the localmode default


Mark Drew

**Comment by cybersonic** [comment]
Thinking about it. I really think we SHOULDNT put local.result because variables not being local by default in functions is an error , historical or not. 

Putting local.something in the code samples just highlights it and shows what a dumb language CFML can be at times. 

Mark Drew

**Pull request merged**
