### PR TITLE
add Lucee Step Debugger Installation Guide

### PR DESCRIPTION
**Pull request by andreasRu**

### CODE REVIEW

**Comment by zspitzer** [comment]
lovely, would you like to add this to the getting started page?

https://docs.lucee.org/guides/getting-started/lucee-editors-IDEs.html

that page could also be re-prioritised, cfeclipse can be removed, dictionary stuff can 
go at the bottom, this content can be linked via the VS Code section, which should be first

the path mappings are trickey and I got stuck myself, the example should include a mapping fo server paths to client paths (i.e. docker), if they are wrong, breakpoints don't stick

https://github.com/softwareCobbler/luceedebug?tab=readme-ov-file#vs-code-extension-configuration

**Comment by andreasRu** [comment]
@zspitzer good point! I've tried using `pathTransforms` and the directive is being ignored when setting the breakpoints. The server sees the correct files, but the breakpoints aure unbound using wrong server path. Still looking into it. Please do not merge this PR until I make the changes. I'll notify you as soon I have gathered more informations. This PR is still faulty and need changes. Maybe I should close it and make a full new PR when ready?

**Comment by zspitzer** [comment]
why close, just update it

**Comment by zspitzer** [comment]
I did update that stuff myself, I'm happy to merge this and then you can do a follow up PR to improve it?

**Comment by andreasRu** [comment]
No need to. I have finished it yesterday,  going to do a recheck because I did various changes.

Another important issue is: I think the latest downloadable version doesn't notify the breakpoints correctly with pathTransform.
https://github.com/softwareCobbler/luceedebug/issues/55

**Comment by andreasRu** [comment]
Added and fixed stuff. I've merged the latest master into this PR branch. Now Linter failed with checking some other stuff (outside my changes). I was about to fix those, but didn't want to mix up changes coming from other merges. Letting this here for you to decide how to do it. Hope I didn't add additional work.

**Comment by zspitzer** [comment]
https://docs.lucee.org/guides/Various/lucee-step-debugger-installation-guide.html
https://docs.lucee.org/guides/getting-started/lucee-editors-IDEs.html

fixed the linting errors, my mistakes...

**Pull request merged**
