### PR TITLE
LD-75 - Updating the CFGrid page to remove the attributes and adding message

### PR DESCRIPTION
**Pull request by andrew-dixon**
Updating the CFGrid page to remove the attributes and adding message about it not being supported in Lucee.

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@DominicWatson If you are happy with this approach I will get on with the request.

**Comment by DominicWatson** [comment]
Awesome - let me pull it down locally and take it for a spin

**Comment by DominicWatson** [comment]
I think a simpler message is appropriate. 'Unfortunately' puts some negative opinion on it - one might argue, "The cfgrid tagis not support, thank goodness" ;)

I suggest:

> The `<cfgrid>` tag is not supported by Lucee.

**Comment by DominicWatson** [comment]
@andrew-dixon note the backticks surrounding the cfgrid tag to show as code rather than using `&lt;`, etc. Cleaner I think.

**Pull request merged**
