### PR TITLE
Adding a building from the source link

### PR DESCRIPTION
**Pull request by cybersonic**

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@cybersonic don't think that will be the right link as the page is here:

http://docs.lucee.org/guides/working-with-source/build-from-source.html

so I think it would be:

working-with-source-building-from-the-source

**Comment by cybersonic** [comment]
ok, then I shall edit that page as it’s missing the latest stuff

**Comment by sbleon** [comment]
@cybersonic, @andrew-dixon I'd love to see the Build From Source page updated. I'm having trouble trying to run the test suite.

**Comment by andrew-dixon** [comment]
@sbleon - You might find the answer in this video that @michaeloffner did at dev.Objective https://www.youtube.com/watch?v=4KIqWLr768M

**Comment by bdw429s** [comment]
@andrew-dixon @DominicWatson Is this pull ready to be merged?

**Comment by DominicWatson** [comment]
No, I've just gone and updated the link directly in master as per Andrew's suggestion though. Closing this PR.

**Pull request closed without merging**
