### PR TITLE
Update _examples.md

### PR DESCRIPTION
**Pull request by bharat20185**
To initialize param (accumulator) in the closure will give an error when there is no record in the query. I would like the "Documented way".

### CODE REVIEW

**Comment by andrew-dixon** [comment]
The second way doesn't error when there are no records, it returns "null" which in turn means the variable doesn't exist and then causes the dump to error. 

Both methods are there to show different ways, so maybe the better option would be to have both run and output their results to show that both work. 

Maybe also have the initial value of age in the second version set to a different number, say 10 to show the difference it makes.

**Comment by bharat20185** [comment]
@andrew-dixon I agreed. It would be a better option to have both runs.

**Comment by andrew-dixon** [comment]
@bharat20185 If you could update this pull request to reflect that, then I can get it merged 😄

**Comment by bharat20185** [comment]
@andrew-dixon I create a pull request #668

**Pull request closed without merging**
