### PR TITLE
Add missing cfscript example for cfwddx

### PR DESCRIPTION
**Pull request by dbelanger**
It took us a while to figure this one out so to save the next dev some  time, an example will do just fine.

### CODE REVIEW

**Comment by zspitzer** [comment]
that example will crash, can you provide a strWDDX and then dump out the result?

**Comment by dbelanger** [comment]
This should now be ready to go Zac.  I only added this example because the script implementation is different than the implementation in Adobe CF.  The Adobe CF is a function call:
`cfwddx(action='wddx2cfml', input=strWDDX, output='example');`
and the Lucee script version wasn't written anywhere... Took us a while to figure it out (and honestly, I just got lucky...) so I thought this would help others

**Comment by zspitzer** [comment]
thanks! can you fix the markdown link warning?

**Comment by dbelanger** [comment]
I cannot as I have no idea what it's talking about

**Comment by dbelanger** [comment]
I used GitHub's own markdown editor to create this patch so the markdown should be valid...  I don't understand the error

**Comment by zspitzer** [comment]
see https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines

**Comment by dbelanger** [comment]
It failed because it needed a blank line before a tag block? 

I originally wanted to add a single line to the docs just to help others avoid my pain in trying to find the correct script syntax... While I can appreciate you wanting a little more in the sense of an example, the effort required to passed all the tests isn't very encouraging to a first time contributor... Anyway, it's been corrected (again)

**Comment by zspitzer** [comment]
thanks for improving the docs! 

sorry for the linting frustration

**Pull request merged**
