### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by jbampton**
Optimize the images with lossless compression.

https://imgbot.net/docs/

*Total -- 668.91kb -> 655.96kb (1.94%)

/luceelogoicon.png -- 12.97kb -> 10.49kb (19.13%)
/builders/dash/resources/icon.png -- 1.64kb -> 1.34kb (17.89%)
/builders/html/assets/images/lucee-logo.png -- 1.88kb -> 1.77kb (5.83%)
/builders/html/assets/css/fonts/MaterialDesignIcon.svg -- 326.82kb -> 321.02kb (1.78%)
/builders/html/assets/css/fonts/fontawesome-webfont.svg -- 306.05kb -> 301.86kb (1.37%)
/builders/html/assets/images/samples/landscape.jpg -- 19.55kb -> 19.48kb (0.33%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>

Co-authored-by: John Bampton <jbampton@users.noreply.github.com>

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@jbampton Not sure why, but this request is saying you haven't signed the CLA and will not let me merge it until you do. Do you mind doing it again from this one. Thanks.

**Comment by andrew-dixon** [comment]
@jbampton Actually, I found the problem, it was because imgbot made the commit. I've worked around the CLA issue.

**Comment by andrew-dixon** [comment]
@jbampton Thanks.

**Comment by jbampton** [comment]
Thanks once again @andrew-dixon :)

**Pull request merged**
