### PR TITLE
Add Render Function

### PR DESCRIPTION
**Pull request by zspitzer**

### CODE REVIEW

**Comment by DominicWatson** [comment]
Hey @zspitzer, thanks for this. The only caution I have is with the example. If using `trycf` we should ensure that the code sample will run without error in TryCF. So something other than a cfmail example would be good :)

Could you revise the example (and test it directly in TryCF)?

**Comment by zspitzer** [comment]
Can next week, I'm off bushwalking!

**Comment by DominicWatson** [comment]
Had to revert this due to breaking build. There was also an underlying problem with the `render()` method being missing from the docs - the docs were being built in Lucee 4! I've updated the build to run with Lucee 5 and imported all the missing tags and functions so we now have a skeleton function definition for the `render()` method.

Will add basic docs to that based on your PR @zspitzer.

Thanks again for the contrib.

**Comment by zspitzer** [comment]
Just noticed it's showing up as render, rather than Render in the function list http://docs.lucee.org/reference/functions.html

**Pull request merged**
