### PR TITLE
Ld 76

### PR DESCRIPTION
**Pull request by micstriit**

### CODE REVIEW

**Comment by DominicWatson** [comment]
I'm a little torn on this one. The piece around default values is all fine (and this should be two separate pull requests). However, the hiding of deprecated pages in this way isn't quite right.

If we don't want a page to appear in the documentation, we need to either delete it completely, or provide the page and show a note about it not being implemented (as @andrew-dixon has been starting to do with `cfgrid`, etc.)

The pages exist in the repo from an initial import that did check the status flag, the code was skipping importing hidden features which it defined like so:

```private boolean function _isHiddenFeature( required struct feature ) {
	return arguments.feature.name.startsWith( "_" ) || ListFindNoCase( "hidden,unimplemeted", arguments.feature.status ?: "" );
}```

So, if that was missing certain functions, then the problem was with the import.

The main thing to understand is that the docs are driven editorially from the content structure. Function and Tag type pages are then *augmented* with data from the source. If we don't want a function/tag to be in the docs, we should delete the page editorially. However, I think we should probably be including the pages and showing the "Not implemented" note.

**Comment by micstriit** [comment]
important is that "deprecated" and hidden are not the same thing, for example there are some function where the name starts with "_" and have set status=hidden, this function are sown in the doc but they really should not. they are for internal use only, the compiler is using them to link certain syntax to functions. in my opinion if they are not imported in the first place my functionality for this is not necessary. but if they are imported my implemention is just an issurance that they are not shown. is not no harm in that test even it is not necessary in best case.
when it comes to "unimplemeted" this is an discussion we have to do with andrew, but one thing is sure, atm they are shown as regular functionality with no information that they are not supported, this of course need to change asap.

**Comment by andrew-dixon** [comment]
@micstriit - All the "unimplemented" tags have already been updated to show the "unimplemented" note and the functions are coming very soon, started on them last night. 

I can't find the "hidden" functions (starting with an underscore "_") in the documentation, so I don't think that is actually a problem.

With regards to "deprecated", I would say that these should be marked as "deprecated" at the top of the page with a very obvious message  (e.g. https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingCustomVariables?hl=en)  saying that the tag/function is deprecated in Lucee and we suggest using X instead.

**Comment by DominicWatson** [comment]
Agreed Micha - I just don't think the 'not implemented' pages should disappear completely and I wouldn't want pages in the documentation that didn't show up. Once we've tidied up the existing problematic functions and tags I think we should re-evaluate. 

And yes, the hidden functions and tags should never show - afaik, the import succesfully blocked those out.

**Comment by DominicWatson** [comment]
I'm going to close this. There is an open ticket for sorting out all the missing functions, etc. that needs to be done. I don't think that this is the right implementation.

**Pull request closed without merging**
