### PR TITLE
Add documentation for `cfdocument`'s new `type` attribute

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by zspitzer** [comment]
Can you add a since version?

**Comment by sbleon** [comment]
Yup. Do you know of any existing places that have such an annotation? I'd
like to keep things consistent.

**Comment by zspitzer** [comment]
Via tag definitions we show it as follows

https://docs.lucee.org/reference/functions/queryrowbyindex.html

**Comment by sbleon** [comment]
@zspitzer done!

**Pull request merged**
